name: post_it
description: "A new Flutter project."
publish_to: 'none'

# App Version
version: 1.0.0+1

# SDK
environment:
  sdk: ^3.5.2

# All Dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  font_awesome_flutter: ^10.7.0
  dio: ^5.7.0
  auto_size_text: ^3.0.0
  showcaseview: ^3.0.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0

# All Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


# All Flutter App Material
flutter:
  uses-material-design: true

  # Resources Path
  assets:
     - assets/images/

  # Fonts
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/post_it.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/post_it.png"